"""dates added

Revision ID: b18fe1f4ebce
Revises: fd4c5e708f96
Create Date: 2024-03-24 21:37:46.139766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b18fe1f4ebce'
down_revision: Union[str, None] = 'fd4c5e708f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('date_valid_until', sa.DateTime(), nullable=False))
    op.add_column('expense', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('income', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income', 'date')
    op.drop_column('expense', 'date')
    op.drop_column('budget', 'date_valid_until')
    # ### end Alembic commands ###
